### ISSUE TITLE
New Featues

### ISSUE THREAD

**Issue by Aeternus185** [mpolden/echoip#101]
Hello, would it be possible to add new features to make it as advanced as this website?  http://f.vision/
I can pay for it

**Comment by maximbaz** [comment]
Hi, could you be more specific about the features you are interested in?

Remember this project's goal is to lookup an IP address and provide some extra information about the IP address, it's not a privacy checker / security analysis / anonymizer detector tool, so I would say things like "canvas fingerprint detection" are definitely out of scope. But if you have some ideas on what other information about an IP address we can provide, we can think about it 🙂

**Comment by maximbaz** [comment]
Closing for now, but please post an update here if you come to some proposal.
