### ISSUE TITLE
Hosting sponsor

### ISSUE THREAD

**Issue by dhrp** [mpolden/echoip#103]
Hi Martin! 

Since someone pointed me to ifconfig.co I've been somewhat of a fan of this service; however trivial it may seem.. 

(But) since I'm now also using it on a regular basis I've noticed occasional Heroku error messages. -- not sure what causes them, but it suggests that you either have more load than Heroku likes or something else. 

Now.. Since I'm working on GreenEdge a new _and sustainable_ cloud provider, I figured perhaps we can sponsor hosting this service with more power and everything. -- you would still be the maintainer (and owner) of the service, and all that we ask in return is a small line saying that we're supporting this project.

hope to hear from you and greetings!
Thatcher

**Comment by mpolden** [comment]
Sounds great! I've sent you an email, lets continue the discussion there.

**Comment by maximbaz** [comment]
Hi guys, I received a note saying that `ifconfig.co` suddenly started responding with `HTTP 429` way too often recently, while I don't have any data to back this up I thought it might be related to a recent hosting change. If so, please consider having a look and potentially relaxing some limits, a simple caching service in front of the service would be more appreciated than `429` error. Thanks 🙂

**Comment by mpolden** [comment]
Total traffic increased even more over the past week.

Rate limit is there to discourage abusive traffic. You can currently do 10 requests per minute before being rate limited (leaky bucket), that averages out to 1 request every 6 second. What is the use case for querying more often than that?

**Comment by maximbaz** [comment]
In that specific case it was the Azure DevOps build pipeline that queried `ifconfig.co` to get the public IP address of the build agent the job is running on. The pipeline didn't run for days, and on the very first run that day it got `429` error. I can only assume that there are tons of different stuff by different people running on Azure build agents across the world, all of them reusing the same agents and the same IP addresses, and some of them querying `ifconfig.co`, and as soon as that hits 10 requests, the service responds with `429` for everyone else.

**Comment by mpolden** [comment]
Ok, I've relaxed the rate limiting a bit now. 🙂
