### ISSUE TITLE
echoip --trusted-header=X-Forwarded-For does not work as expected with nginx

### ISSUE THREAD

**Issue by HerrBlauzahn** [mpolden/echoip#107]
Good evening,

I know, this question has been asked a lot. But I just can't find my error here.
I run echoip through the official docker image as follows:
`sudo docker run --detach --name echoip --restart unless-stopped -p 127.0.0.1:19980:8080 mpolden/echoip echoip --port-lookup --reverse-lookup --trusted-header=X-Forwarded-For`

But when I access the page, it only shows the internal IP `172.17.0.1`.

I even wrote a little PHP Script that runs on a second webserver that dumps the request headers. It shows the correct IP for the HTTP header `X-Forwarded-For`.
The only thing that I changed in the nginx config was the port to proxy.
So the header should work as expected.

Here is my proxy location block from the nginx config:
```
location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://127.0.0.1:19980/;
}
```

**Comment by maximbaz** [comment]
Hi, your arguments aren't being passed to `echoip` (you would see in the logs that port lookup is enabled, etc)

Try this:

```
# docker run --name echoip --rm -p 127.0.0.1:19980:8080 mpolden/echoip -p -r -H X-Forwarded-For
```

**Comment by HerrBlauzahn** [comment]
Yes, now it works.
So passing arguments with -- does not work? Has this something to do with Docker or is it an issue with echoip?

**Comment by maximbaz** [comment]
I think what happened is that your initial command resulted in the following call:

```
$ echoip echoip --port-lookup ...
```

and when `echoip` receives `echoip` as the first argument, it doesnt throw an error and doesn't process any further arguments.

Will reopen just to double-check that this is the case, if it is the case, we should just throw an error saying that "echoip is an unrecognized parameter" or something like that.

**Comment by maximbaz** [comment]
Turns out this is claimed as "by design" by the Go flags parsing: https://golang.org/pkg/flag/#hdr-Command_line_flag_syntax

> Flag parsing stops just before the first non-flag argument ("-" is a non-flag argument) or after the terminator "--".

There is no reason except "why not", e.g. see here: https://stackoverflow.com/questions/25248534/golang-flag-parsing-after-an-argument-on-command-line

I think we'll just have to use this unless we ever want to change to a different library that parses CLI args.

**Comment by HerrBlauzahn** [comment]
So command arguments passed with `--` don't work? Maybe you should consider changing the help text if arguments like `--port-lookup` don't work. But that's just my educated guess. I'm not really familiar with Go.

Have a nice day ;-)

**Comment by maximbaz** [comment]
Aaah sorry I only now understood what you are asking! 🙂 No I guess since @mpolden converted to using `flag`, there are no more long options, only short ones exist:

https://github.com/mpolden/echoip/blob/832f3655e886b42eaf017c27c3a8c6f3cf523318/cmd/echoip/main.go#L33-L44

But help text for me doesn't show long options, maybe you are looking at the old documentation?

**Comment by mpolden** [comment]
Yes, you have to use short options now. I wanted to the get rid of the go-flags dependency as the requirements of `echoip` are simple enough for the built-in one.

Other than the lack of long options, there shouldn't be any other differences. Short flags are the same as before.

**Comment by HerrBlauzahn** [comment]
Oh so then your [Docker page](https://hub.docker.com/r/mpolden/echoip) is a bit outdated. I took a quick look at it and it still has the old, long, option flags in it. Your GitHub README.md is up to date.
But thanks for the explanation. I appreciate it.

**Comment by mpolden** [comment]
That explains the confusion. I was under the impression it synced automatically, but that appears to be broken. I changed it to a link for now. Thanks!
