### ISSUE TITLE
ifconfig.co is not reachable everywhere

### ISSUE THREAD

**Issue by mbrodala** [mpolden/echoip#110]
The site https://ifconfig.co/ is currently not reachable everywhere. E.g. it works fine for me but not for colleges of mine and also not on our CI build nodes. Is there a DNS change or similar currently in progress?

Here's how this looks like:

```bash
$ curl -sS https://ifconfig.co/
curl: (6) Could not resolve host: ifconfig.co

# Google DNS
$ curl -sS --dns-servers 8.8.8.8,8.8.4.4 https://ifconfig.co/
curl: (6) Could not resolve host: ifconfig.co

# Cloudflare DNS
$ curl -sS --dns-servers 1.1.1.1,1.0.0.1 https://ifconfig.co/
curl: (6) Could not resolve host: ifconfig.co

$ traceroute ifconfig.co
ifconfig.co: Temporary failure in name resolution
Cannot handle "host" cmdline arg `ifconfig.co' on position 1 (argc 1)
```

Connections in general are working:

```bash
$ curl -sS https://example.org/
<!doctype html>
# ...
```

**Comment by webvictim** [comment]
I'm having the same issue. It now seems to work directly using Cloudflare's public DNS servers (1.1.1.1 and 1.0.0.1) but not via Google (8.8.8.8, 8.8.4.4) or OpenDNS (208.67.222.222, 208.67.220.220).

**Comment by mpolden** [comment]
How about now?

**Comment by webvictim** [comment]
Working for me now.

**Comment by mbrodala** [comment]
Yes, it seems to be working again now. What did you do?

**Comment by mpolden** [comment]
It was related to misconfiguration of DNSSEC.
