### ISSUE TITLE
v4.ifconfig.co and v6.ifconfig.co have same DNS records

### ISSUE THREAD

**Issue by markkrj** [mpolden/echoip#111]
It would be useful if v4.ifconfig.co had only A records while v6 had only AAAA.
Of course we can check ipv4 and ipv6 via curl (-4 and -6), but this way we could check ipv4 **and** ipv6 via browser.

![image](https://user-images.githubusercontent.com/13537652/97439825-6ed64880-1905-11eb-9ab7-90248aa0ec06.png)

**Comment by mpolden** [comment]
See the FAQ on https://ifconfig.co. It's a Cloudflare limitation. It's not possible to return only AAAA records for a name combined with proxying.

**Comment by markkrj** [comment]
Just "A" record for v4 also isn't possible? Because v6 will already be preferred by browser...
