### ISSUE TITLE
the latest docker image ignore X-Real-IP

### ISSUE THREAD

**Issue by hieixu** [mpolden/echoip#113]
nginx config:
    location / { 
        proxy_redirect off;
        proxy_pass http://172.17.0.3:8080;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        }

docker command:
docker run -itd --name=echoip   mpolden/echoip /opt/echoip/echoip -H  X-Real-IP

in another host curl shows the docker gateway IP 172.17.0.1
And I try to run echoip in the host and change proxy pass to http://127.0.0.1:8080,
curl show the correct remote IP

direct run shows echoip: Trusting remote IP from header(s): X-Real-IP,
and docker not

**Comment by psyhomb** [comment]
I have noticed similar issue when running `echoip` on Kubernetes on Rpi4 and what's strange is that according to logs it looks like `-H` and several other options aren't supported at all?

```
# kubectl logs -l app=echoip
  -c string
    	Path to GeoIP city database
  -f string
    	Path to GeoIP country database
  -l string
    	Listening address (default ":8080")
  -p	Enable port lookup
  -r	Perform reverse hostname lookups
  -t string
    	Path to template (default "index.html")
```

**Comment by LulzLoL231** [comment]
Same problem, but after recreate docker container, it's works, idk how, but works.

My nginx conf:
```nginx
server {
    include /etc/nginx/options/security.conf;  # some security headers, nvm.
    include /etc/nginx/proxy_params;
    server_name ip.lznet.dev;
    listen 443 ssl;
    location / {
        proxy_pass http://172.17.0.2:8888/;  # Docker IP in docker0 (bridge-net). And echoip port (8888).
    }
    # <сropped> ssl options.
}
```
`/etc/nginx/proxy_params` content:
```nginx
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```
My `docker run` command:
`docker run -itd --name=echoip mpolden/echoip /opt/echoip/echoip -H X-Real-IP -l :8888`

**Comment by mpolden** [comment]
The `Dockerfile` has `/opt/echoip/echoip` as its entrypoint. See https://docs.docker.com/engine/reference/builder/#entrypoint for what this means. You should use
`docker run -itd --name=echoip mpolden/echoip -H X-Real-IP -l :8888`.
