### ISSUE TITLE
Bug: Custom IP query is unable to retrieve specific lookups 

### ISSUE THREAD

**Issue by Eisa01** [mpolden/echoip#116]
Querying custom IP addresses is now possible, however it is not possible to specify the type of lookup when querying a custom IP.
e.g.:

`curl ifconfig.co/?ip=8.8.8.8/json` or `curl ifconfig.co/?ip=8.8.8.8/country` or any other lookup, returns the following:

`Internal server error`

The same error also occurs when using browsers
[https://ifconfig.co/?ip=8.8.8.8/asn](https://ifconfig.co/?ip=8.8.8.8/asn)

**Comment by mpolden** [comment]
Those URLs are invalid. Use `curl ifconfig.co/json?ip=8.8.8.8` for example. The parameter comes after the path.
