### ISSUE TITLE
Website and curl on windows returning reserved IP?

### ISSUE THREAD

**Issue by b1scoito** [mpolden/echoip#118]
![](https://b.catgirlsare.sexy/Tf99fdP_.png)

Title says it all.

**Comment by mpolden** [comment]
The site for this project is ifconfig.co and is unrelated to ifconfig.**io**.

**Comment by visualblind** [comment]
> ![](https://camo.githubusercontent.com/e5b503b1cebd560be129de7135b12b4d3e64c1389a8c4cecdb899210316f1389/68747470733a2f2f622e6361746769726c736172652e736578792f546639396664505f2e706e67)
> 
> Title says it all.

Just wanted to add my 2c. I run the ipconfig.io site and finally figured out why it was returning experimental IP address space instead. The "Pseudo IPv4" option on the Network tab in Cloudflare was set to Overwrite headers. I've disabled it and verified it's now returning the proper ipv6 address for those with v6.

**Comment by b1scoito** [comment]
Thanks for this. This is also not the best place to be selling your domain, please add a alert on your website so people can see.

**Comment by mpolden** [comment]
Removed inappropriate content from both your comments. Discuss it elsewhere.
