### ISSUE TITLE
Unable to access it from a webapp

### ISSUE THREAD

**Issue by geabenitez** [mpolden/echoip#119]
I am getting this error whenever I try to access it from a web app

`Access to XMLHttpRequest at 'https://ifconfig.co/json' from origin 'https://XXXX' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by mpolden** [comment]
This is intentional. If you want it on your own site the best solution is to host it yourself.
