### ISSUE TITLE
echoip with dbip ASN-database

### ISSUE THREAD

**Issue by fflo** [mpolden/echoip#120]
Hi,

do you have a hint how to use echoip with the _dbip_ ASN-database?

Trying to load it with "-a" results into the following error:
`echoip: geoip2: reader does not support the "DBIP-ASN-Lite (compat=GeoLite2-ASN)" database type`

_dbip_ country and city databases seem to work fine.

Thanks

**Comment by mpolden** [comment]
What kind of database is this? The ones defined in the current `Makefile` should work. I haven't tried others.

**Comment by fflo** [comment]
It's these ones: https://db-ip.com/db/lite.php

IP to Country Lite and IP to City Lite works, but not IP to ASN Lite.

**Comment by fflo** [comment]
One more issue using the _dbip_ database(s):
The Maxmind GeoLite2 License text should only be displayed, if this database is used. Is there a way to suppress this message if using another database?

**Comment by mibuthu** [comment]
This should be fixed with [this commit](https://github.com/oschwald/geoip2-golang/commit/969de8ada705525a66caef04eef89777e5f414fd) in geoip2-golang.
So an update of the module to version 1.5 should fix the problem.

**Comment by mpolden** [comment]
> The Maxmind GeoLite2 License text should only be displayed, if this database is used. Is there a way to suppress this message if using another database?

No, but you can specify a custom template with the `-t` option.

**Comment by fflo** [comment]
@oschwald and @mibuthu thanks for the commit fixing this issue. Awesome.
