### ISSUE TITLE
docker install

### ISSUE THREAD

**Issue by GPConnect** [mpolden/echoip#124]
sorry, i tried the docker install but i didn't fully understand it ! 
if i only use this command "docker run --detach --name ifconfig -p 80:8080 mpolden/echoip echoip -p -H X-Forwarded-For" the container does not run ! 
should i add all the options listed in the usage section of the page ? 
i run the maxmind docker container to update the geoip database ! How should i give echoip the database path ! 
thanks for any help !

**Comment by GPConnect** [comment]
understood it :)

**Comment by visualblind** [comment]
> understood it :)

How did you get the container to start while specifying the additional parameters of "echoip -p -H X-Forwarded-For"?
Following the documentation, the container fails to start unless you don't specify any configs. I need to change the host header.

**Comment by GPConnect** [comment]
you actually need to use these parameters for the software to work ! 
my compose file if it can help : 

version: "3.8"
services:
  echoip:
    image: mpolden/echoip
    command: >
      -p
      -r
      -H X-Forwarded-For
      -a /data/GeoLite2-ASN.mmdb
      -c /data/GeoLite2-City.mmdb
      -f /data/GeoLite2-Country.mmdb
    ports:
      - "8888:8080"
    volumes:
      - "/opt/geoip/geoipupdate:/data"
    restart: unless-stopped

i use geoipupdate docker image to keep geoip database updated
https://hub.docker.com/r/maxmindinc/geoipupdate
