### ISSUE TITLE
Flags provided but not defined: docker-compose

### ISSUE THREAD

**Issue by afzl-wtu** [mpolden/echoip#159]
There are other duplicate issues but no one worked for me.
After spending my  6 to 8 hours without eating or drinking anything, I finally found there is a bug in echoip, whenever I run sudo docker-compose up:
![image](https://user-images.githubusercontent.com/64379149/187177970-cef4a4e0-bedb-4877-b059-2ba99b8e5e65.png)

My compose file:
![image](https://user-images.githubusercontent.com/64379149/187178026-a75793fc-dae5-4a4b-a0ee-d7afccde781a.png)

I have tried every possible combination:
"-C 0 -p -r -H X-Forwarded-For -a /data/GeoLite2-ASN.mmdb -c /data/GeoLite2-City.mmdb -f /data/GeoLite2-Country.mmdb"
"-C 0 -p -r -H=X-Forwarded-For -a /data/GeoLite2-ASN.mmdb -c /data/GeoLite2-City.mmdb -f /data/GeoLite2-Country.mmdb"

If I try:
"-H=X-Forwarded-For -a /data/GeoLite2-ASN.mmdb -c /data/GeoLite2-City.mmdb -f /data/GeoLite2-Country.mmdb -p -r"
It considers all other flags and theier values as a value of -H:
![image](https://user-images.githubusercontent.com/64379149/187179251-8100b8a0-3c84-417c-9fb9-e2488ab663b5.png)

If I try: 
"-a /data/GeoLite2-ASN.mmdb -c /data/GeoLite2-City.mmdb -f /data/GeoLite2-Country.mmdb -H=X-Forwarded-For -p -r"
![image](https://user-images.githubusercontent.com/64379149/187179824-aacb91db-9540-49c3-9869-08e81fda95ec.png)

If I try:
"-a=/data/GeoLite2-ASN.mmdb -c=/data/GeoLite2-City.mmdb -f=/data/GeoLite2-Country.mmdb -H=X-Forwarded-For -p -r"
It considers all other flags and their values as value of -a
![image](https://user-images.githubusercontent.com/64379149/187180295-3c7f53f9-b9f7-4acf-9379-4d4de2337428.png)

**Comment by ShlomiPorush** [comment]
did you download GeoIP Files?

**Comment by afzl-wtu** [comment]
> did you download GeoIP Files?

![image](https://user-images.githubusercontent.com/64379149/187181559-4a86a6d2-4e53-426d-991b-b246606a88c9.png)

**Comment by afzl-wtu** [comment]
> did you download GeoIP Files?

Even if I try this:
"-p -r -H=X-Forwarded-For"

![image](https://user-images.githubusercontent.com/64379149/187182611-df3a62dd-1c46-4d9c-9c1b-cc052d58e059.png)

**Comment by ShlomiPorush** [comment]
dont know if it related, why do you use the full path in the volume?
try 
```
    volumes:
      - ./geoipupdate:/data:ro
```

**Comment by afzl-wtu** [comment]
> dont know if it related, why do you use the full path in the volume? try
> 
> ```
>     volumes:
>       - ./geoipupdate:/data:ro
> ```

in my last reply bro you can see volumes or geolite2 is irrelevant. It is pure issue of flags.

**Comment by ShlomiPorush** [comment]
I have no idea where the problem is. In my setup it works fine. 

`-C 0 -p -r -H X-Forwarded-For -a /data/GeoLite2-ASN.mmdb -c /data/GeoLite2-City.mmdb -f /data/GeoLite2-Country.mmdb -t /html`

**Comment by afzl-wtu** [comment]
> I have no idea where the problem is. In my setup it works fine.
> 
> `-C 0 -p -r -H X-Forwarded-For -a /data/GeoLite2-ASN.mmdb -c /data/GeoLite2-City.mmdb -f /data/GeoLite2-Country.mmdb -t /html`

Strange, I just copied your docker-compose in a new a.yaml file and changed volume mapping to mine one, and now everything is working fine.
sudo docker-compose -f  a.yaml up. Thanks for your quick response and help. But I will pposr both files here may be some UTF text issue.

**Comment by afzl-wtu** [comment]
Not Working:
```version: '3.7'
services:
  echoip:
    image: mpolden/echoip
    volumes:
      - "/home/afzl/@Apps/geoip/geoipupdate:/data"
    command:
      - "-C 0 -p -r -H X-Forwarded-For -a /data/GeoLite2-ASN.mmdb -c /data/GeoLite2-City.mmdb -f /data/GeoLite2-Country.mmdb"
    ports:
      - "2087:8080"```

Working Fine:
```version: '3.7'

services:
  echoip:
    image: mpolden/echoip
    command: "-C 0 -p -r -H X-Forwarded-For -a /data/GeoLite2-ASN.mmdb -c /data/GeoLite2-City.mmdb -f /data/GeoLite2-Country.mmdb"
    ports:
      - 2087:8080
    volumes:
      - /home/afzl/@Apps/geoip/geoipupdate:/data```
