### ISSUE TITLE
Why were the v4 and v6 subdomains removed?

### ISSUE THREAD

**Issue by dumbasPL** [mpolden/echoip#185]
Hi,
I'm wondering why were the v4 and v4 subdomains removed. Many clients (including browsers) don't have an easy way to force one over the other. I configured these domains on my own instance and they seem to work perfectly. Aside from two additional DNS entries, they don't seem to require anything special to work, so why remove them? Am I missing something obvious that I should know?

**Comment by kolobus** [comment]
Most copies use CloudFlare proxy to cover instance and CF doesn't allow to disable IPv6 anymore.

**Comment by dumbasPL** [comment]
makes sense
