### ISSUE TITLE
allow user to explicitly specify ipv4 or ipv6 results

### ISSUE THREAD

**Issue by ghost** [mpolden/echoip#2]
like http://ipv4.icanhazip.com/ or http://v4.ident.me/
this is helpful when you need to get the ip of a proxy that you don't control. so if i talk ipv4 to the proxy, but the proxy talks ipv6 to ifconfig.co, i'll only get back ipv6 results.

**Comment by LukeHandle** [comment]
Is this public anywhere else about the other address available?

**Comment by martinp** [comment]
No, I don't think I have documented it anywhere.

**Comment by porjo** [comment]
+1 for documentation. This should at least be documented on the main web page (when visited via browser). Thanks for a great utility!

**Comment by porjo** [comment]
I just hit this issue again after moving house. It'd be great if the ipv6 page also had a link to the ipv4 version of the page...or some hint as to how to get there.
