### ISSUE TITLE
Using behind nginx/apache

### ISSUE THREAD

**Issue by xtavras** [mpolden/echoip#4]
Hi Martin,
I 'd like to use this app behind web server like apache or nginx, but if I do so (with mod_proxy for apache or proxy_pass for nginx) I see IP address of server itself and not of client.  ifconfig.co runs behind nginx, right? so its possible I assume, but how? Thanks for your help.

**Comment by redlegoman** [comment]
This does not work for me. I have the config in nginx exactly as above, but when I access the URL from the internet, the IP address show by ipd is the local IP of the nginx reverse proxy, not the IP address of the remote client. The remote client address does show in the nginx logs.

**Comment by redlegoman** [comment]
Sorry, forget this. I just noticed the -H option. -H X-Real-IP sorts it.
