### ISSUE TITLE
`curl ifconfig.co` returning CAPTCHA instead od IP address

### ISSUE THREAD

**Issue by outlying** [mpolden/echoip#74]
Right now  `curl ifconfig.co` is returning HTML with CAPTCHA instead of IP addres

```
<head>
<title>Attention Required! | Cloudflare</title>
<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script><!--<![endif]-->




</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> ifconfig.co</h2>
      </div><!-- /.header -->
      
      <div class="cf-section cf-highlight cf-captcha-container">
```

Obviously other commands are not working too, retuning HTML instead od IP address, I believe it's some sort of misconfiguration but I might be wrong.

**Comment by mpolden** [comment]
Due to the popularity of https://ifconfig.co (and increase in abusive traffic patterns) I had to put it behind Cloudflare some time ago. I have very little control over the heuristics Cloudflare uses to show that captcha and I have no interest in manually whitelisting IPs/subnets/ASNs.

If Cloudflare always gives you a captcha, I would suggest running `echoip` yourself (it can e.g. easily be deployed for free on Heroku), or using another similar service.

Thanks for understanding!

**Comment by outlying** [comment]
Well I do understand, however your guidelines included on the front page are not working right now, and if they might not work in the future it might be a good idea to take them down, so they won't confuse people they might not understand why whose command are not working.

**Comment by smed79** [comment]
alternative
```
curl eth0.me
curl icanhazip.com
curl checkip.amazonaws.com
curl ifconfig.me
curl ipecho.net/plain
```

**Comment by y377** [comment]
> alternative
> 
> `curl -s ifconfig.co | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}'`
> 
> or
> 
> ```
> curl eth0.me
> curl icanhazip.com
> curl checkip.amazonaws.com
> curl ifconfig.me
> curl ipecho.net/plain
> ```

You are very good. Can you help me build one for Chinese users to inquire?

**Comment by JasonTable** [comment]
> Due to the popularity of https://ifconfig.co (and increase in abusive traffic patterns) I had to put it behind Cloudflare some time ago. I have very little control over the heuristics Cloudflare uses to show that captcha and I have no interest in manually whitelisting IPs/subnets/ASNs.
> 
> If Cloudflare always gives you a captcha, I would suggest running `echoip` yourself (it can e.g. easily be deployed for free on Heroku), or using another similar service.
> 
> Thanks for understanding!

You don't have to whitelist IP addresses. Just whitelist the "T1" country in the control panel. For anyone else who sees this. Use ifconfig.me. they don't have this Cloudfail bull****.
