### ISSUE TITLE
I built it on my server. After making, the access is abnormal

### ISSUE THREAD

**Issue by RokasUrbelis** [mpolden/echoip#79]
hi！I built it on my server. after making, the access is abnormal
![image](https://user-images.githubusercontent.com/48517501/73853691-3e78e680-486c-11ea-93ef-6e53d75742a3.png)

![image](https://user-images.githubusercontent.com/48517501/73853525-f954b480-486b-11ea-877e-1e9c21d24df5.png)

**Comment by allcloud-jonathan** [comment]
Looks like you opened the template instead of running the binary as described in the [usage section](https://github.com/mpolden/echoip#usage-1) of the Readme.

Did you run `echoip [...]` on that domain?

**Comment by RokasUrbelis** [comment]
> Looks like you opened the template instead of running the binary as described in the [usage section](https://github.com/mpolden/echoip#usage-1) of the Readme.
> 
> Did you run `echoip [...]` on that domain?

yeah,can run as you said,but I want to listen  80 with virtual host,the information notice can't work
![image](https://user-images.githubusercontent.com/48517501/75767066-2322cd80-5d7d-11ea-83d3-0a1d60a8dcba.png)

**Comment by RokasUrbelis** [comment]
> Looks like you opened the template instead of running the binary as described in the [usage section](https://github.com/mpolden/echoip#usage-1) of the Readme.
> 
> Did you run `echoip [...]` on that domain?

thanks,resolved.
I have another problem,I did a rewrite and jumped to 'https'. as a result, the CLI must use 'https' to obtain IP information. Is there a way for a browser to access 'http' and it can jump to 'https'? CLI access to http can have IP information. very thank!!

**Comment by mpolden** [comment]
> Is there a way for a browser to access 'http' and it can jump to 'https'?

Yes, it's called redirection. `echoip` itself doesn't provide this, so you should use Nginx or Apache as a reverse proxy if you need this feature.
