### ISSUE TITLE
Using curl gives me Cloudflare Errors

### ISSUE THREAD

**Issue by louis-ad** [mpolden/echoip#80]
I found this service a while ago, I've been using it to get my external IP so I can update my dynamic DNS configuration (with a cron job that runs hourly). But trying to get the site using curl gives me Cloudflare's "captcha" page.

I don't think I'm hitting the rate-limit - am I?

It's a bit useless if Cloudflare is preventing people with curl from using the service, as the first example is actually curl...

**Comment by louis-ad** [comment]
Closing the issue, I didn't notice the closed issues which is similar to this.

Well... I suppose you need to make a note on the instruction page if the service you're offering won't work reliably, and rewrite it to tell users how to install the service on Heroku...

**Comment by smed79** [comment]
https://github.com/mpolden/echoip/issues/74
