### ISSUE TITLE
Running echoip on Dokku - problem with real IP

### ISSUE THREAD

**Issue by franzos** [mpolden/echoip#81]
Has anyone had any success running `echoip` on [dokku](http://dokku.viewdocs.io/dokku/)?

Here's where I stand:

1. Add new dokku app
2. Push `echoip` repo using [dockerfiles deployment](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/)
3. Set `--trusted-header=X-Forwarded-For` for `run`
4. Configured letsencrypt

```
=====> domain.org docker options information
       Docker options build:                                   
       Docker options deploy:      --restart=on-failure:10  
       Docker options run:         --trusted-header=X-Forwarded-For 
```

I can successfully access the instance at `https://domain.org` but the IP shown is `172.17.0.1`.

I assumed that `--trusted-header=X-Forwarded-For` would resolve this, but it doesn't seem to have any effect whatsoever, even though this header is set in the NGINX config and presumably correct?

```
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Request-Start $msec;
```

**Comment by allcloud-jonathan** [comment]
Maybe https://github.com/mpolden/echoip/issues/4 helps?

**Comment by franzos** [comment]
@allcloud-jonathan thanks for your suggestion! It seems #4 is the same, just that the poster is using `X-Real-IP` rather than `X-Forwarded-For`. This shouldn't make a different, right?

1. nginx config: `proxy_set_header X-Forwarded-For $remote_addr;` _dokku default_
2. Set _echoip_ to grab the IP from `X-Forwarded-For`
   - `-H X-Forwarded-For` - doesn't work
   - `--trusted-header=NAME` doesn't work

I could try with `X-Real-IP` but then I'd have to modify the default _dokku_ config. However, what I'm trying to do, should work just fine. _NGING_ appears to have the correct IP in the logs.

I'll play around a little more over the weekend. Maybe I'm missing something.

**Comment by mpolden** [comment]
`-H X-Forwarded-For` should work. I'm not familiar with Dokku and its network configuration, but have you verified that `$remote_addr` contains the address you expect? Depending on Dokku's network setup it may contain a private IP address of some sort.

**Comment by heyarne** [comment]
mpolden is correct to say you should use `X-Forwarded-For`. You can configure dokku like thise to make sure ifconfig respects that header:

```
ssh dokku@your-server.net config:set ifconfig DOKKU_DOCKERFILE_START_CMD='--trusted-header=X-Forwarded-For'
```

This should be the only configuration that you need.

**Comment by franzos** [comment]
@heyarne that's exactly what I needed. Thanks so much!
