### ISSUE TITLE
Main Website having CloudFlare Block

### ISSUE THREAD

**Issue by Fabricio20** [mpolden/echoip#83]
Hey, not sure if this is the right place to report this but the main website (ifconfig.co) is showing the CloudFlare captcha page for all requests, this might be breaking scripts that make use of the `/ip` endpoint.

If this is intentional please disregard this issue.

**Comment by maximbaz** [comment]
It is - see 3 out of 4 closed issues which ask the same question 🙂

**Comment by Fabricio20** [comment]
Oh oops, sorry for this! Thanks for the quick answer however.

**Comment by smed79** [comment]
https://github.com/mpolden/echoip/issues/74

**Comment by JasonTable** [comment]
wow this is just bad site design imo
