### ISSUE TITLE
running it behind reverse proxy: not able to read x-forwarded-for header

### ISSUE THREAD

**Issue by manipulator01** [mpolden/echoip#90]
Hello,

I setup my own server with this codebase. It was very simple to create and run my docker container to get up and running... however, script is not able to read Cloudflare x-forwarded-for headers properly.

When I access to my website, I see Cloudflare's IP address, not my own laptops IP.

How can I fix this?

**Comment by SuperSandro2000** [comment]
I did not test this but I think you might wanna try this header ``CF-Connecting-IP``. Source https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

**Comment by manipulator01** [comment]
Thanks for your response @SuperSandro2000 

Would you be able to kindly tell me what part of the code do I need to change? 
I don't have much development experience :(

**Comment by SuperSandro2000** [comment]
If you take a look at the help of echoip you can find the ``--trusted-header`` parameter.
So just start echoip like: ``./echoip --trusted-header CF-Connecting-IP``
