### ISSUE TITLE
Weird response for port check

### ISSUE THREAD

**Issue by m4k5ym** [mpolden/echoip#91]
Hello,

I tried the port check for port 80 with following command: `curl https://ifconfig.co/port/80`

On my server with open port 80 I receive a valid response like this:

`{"ip":"127.0.0.1","port":80,"reachable":true}`

If I run the same command from my client I just receive following error message:

```
 Application error

An error occurred in the application and your page could not be served.
If you are the application owner, check your logs for details.
You can do this from the Heroku CLI with the command
heroku logs --tail
```

Actually I expected a response like this:

`{"ip":"127.0.0.1","port":80,"reachable":false}`

**Comment by SuperSandro2000** [comment]
Can't reproduce this neither with the online or my self hosted server.

**Comment by m4k5ym** [comment]
It seems like it have been a hiccup.
