### ISSUE TITLE
Support for ARMHF/ARM64

### ISSUE THREAD

**Issue by TTP1106** [mpolden/echoip#96]
Please add also Support for ARM64

**Comment by SuperSandro2000** [comment]
You should be able to build the Dockerfile on those platforms.

**Comment by ruanbekker** [comment]
Hey @TTP1106 , you can have a look at this [Dockerfile](https://github.com/pistacks/echoip/blob/master/Dockerfile) that I'm using for my raspberry pi

**Comment by TTP1106** [comment]
Hi @ruanbekker thanks for your Reply. I am running out of Memory using your Dockerfile on a OrangePi Zero ARM64. I attached also a USB-Device with 1 GB to extend it, but that seems not enough either.
Any solution to pre-build a container? Running it should not be a Problem but compiling those.

**Comment by maximbaz** [comment]
arm64 architecture is now being prebuilt and published on docker hub 🎉 

![image](https://user-images.githubusercontent.com/1177900/84706977-33426f80-af5e-11ea-9579-b4beccb28e47.png)

Let me know if something is off, otherwise enjoy! 🙂
