### ISSUE TITLE
Getting IPv6 instead of IPv4

### ISSUE THREAD

**Issue by hristo-mavrodiev** [mpolden/echoip#97]
Using the command:
``` bash
curl ifconfig.co
curl ifconfig.co/ip
wget -qO- ifconfig.co
```
on a remote debian10 server deployed by vultr.com doesn't return my IPv4 address.
![image](https://user-images.githubusercontent.com/61916767/83056628-70ea6180-a05e-11ea-9aaf-863c2f79b1f8.png)

Thanks

**Comment by SuperSandro2000** [comment]
Try ``curl ifconfig.co/ip -6``

**Comment by hristo-mavrodiev** [comment]
Thanks, worked with ``` -4```.
